// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package database

import (
	"database/sql"
	"time"
)

type Person struct {
	ID         int64
	CreatedAt  time.Time
	UpdatedAt  time.Time
	Prefix     sql.NullString
	FirstName  string
	MiddleName sql.NullString
	LastName   string
	Suffix     sql.NullString
}

type Prefix struct {
	ID   int16
	Name string
}

type Suffix struct {
	ID   int16
	Name string
}
