version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    ports:
      - 127.0.0.1:5432:5432
      - "[::1]:5432:5432"
    secrets:
      - postgres_password
    volumes:
      - ./local/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
#  api:
#    image: nomenclator/api
#    restart: always
#    secrets:
#      - postgres_password
#    depends_on:
#      - db
#    build:
#      context: ./services/api

secrets:
  tls_cert:
    file: ./secrets/localhost.pem
  tls_cert_key:
    file: ./secrets/localhost_key.pem
  postgres_password:
    file: ./secrets/postgres_password.txt
