version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    ports:
      - 127.0.0.1:5432:5432
      - "[::1]:5432:5432"
    secrets:
      - postgres_password
    volumes:
      - ./local/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB: nomenclator
  api:
    image: us-east1-docker.pkg.dev/pboyd-io/nomenclator/api:${BUILD_TAG:-dev}
    build:
      context: ./services/api
    restart: unless-stopped
    depends_on:
      - db
    secrets:
      - postgres_password
      - tls_cert
      - tls_cert_key
    ports:
      - 127.0.0.1:8080:8080
      - "[::1]:8080:8080"
    environment:
      CERT_FILE: /run/secrets/tls_cert
      KEY_FILE: /run/secrets/tls_cert_key

secrets:
  tls_cert:
    file: ./secrets/localhost.pem
  tls_cert_key:
    file: ./secrets/localhost_key.pem
  postgres_password:
    file: ./secrets/postgres_password.txt
